name: Build ESP-IDF Project

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:v5.4.1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with ESP-IDF
      run: |
        . $IDF_PATH/export.sh
        cd Source
        rm -f sdkconfig
        rm -rf build
        idf.py set-target esp32
        idf.py build
        esptool.py --chip esp32 merge_bin \
          --fill-flash-size 8MB \
          -o build/merged-firmware.bin \
          0x1000  build/bootloader/bootloader.bin \
          0x8000  build/partition_table/partition-table.bin \
          0x10000 build/ESP32PP.bin

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          Source/build/merged-firmware.bin
          Source/build/flasher_args.json